### PR TITLE
fix

### PR DESCRIPTION
**Pull request by Bl4ck-h00d**
I guess, I messed up last time. Please review this.

### CODE REVIEW

**Comment by mozfreddyb** [comment]
@Bl4ck-h00d Can you please fix the issues reported above? It's mostly style/newline things. You can fix them by installing the devDependencies and running the autolint scripts (mentioned in package.json). I will review afterwards.

**Review by mozfreddyb — CHANGES_REQUESTED** [review]
Please fix the lint errors.

**Comment by Bl4ck-h00d** [comment]
Done!

**Review by mozfreddyb — APPROVED** [review]

**Comment by mozfreddyb** [comment]
Thanks!

**Pull request merged**
